/* Telink SWire (single-wire slave) master, waveform-generated by SPI1 + DMA.
 * The cell encoding/decoding lives in swire_codec.h; this is the hardware half. */
#ifndef SWIRE_H
#define SWIRE_H
#include <stdint.h>
#include "protocol.h"
#include "swire_codec.h"

extern sw_cfg_t sw_cfg;

void sw_init(void);
void sw_apply_cfg(void);              /* re-programs SPI after a cfg change  */

/* Target power.  `rails` is a PWR_RAIL_* mask; sw_power() uses both.
 * Switching off always drops both rails regardless of the mask. */
void sw_power_mask(int on, uint8_t rails);
void sw_power(int on);
int  sw_powered(void);
uint8_t sw_power_rails(void);         /* rails currently asserted, 0 = off   */

/* Both return 0 on success, negative on buffer overflow / decode failure. */
int  sw_write(uint32_t addr, const uint8_t *data, uint32_t len);
int  sw_read(uint32_t addr, uint32_t len, uint8_t *out, uint8_t *echo);

/* Power-cycle, then hammer `count` write frames into the post-reset window
 * where the SWire slave will accept activation.  Returns frames sent. */
uint16_t sw_activate(uint16_t count, uint32_t addr, uint8_t data);

/* Interleave a read into the activation burst, entirely in firmware, and stop
 * as soon as the target answers.  Returns the frame index at which it replied,
 * or 0xFFFF if it never did. */
uint16_t sw_activate_read(uint16_t count, uint32_t wr_addr, uint8_t wr_data,
                          uint32_t rd_addr, uint32_t rd_len,
                          uint8_t *out, uint8_t *echo);

/* SPI-NOR flash through the target's MSPI controller, driven entirely on the
 * bridge so a block costs one USB round trip instead of ten. */
int  sw_flash_read(uint32_t addr, uint32_t len, uint8_t *out);
int  sw_flash_write(uint32_t addr, const uint8_t *data, uint32_t len);

/* Loopback check of encode -> SPI -> sample -> decode.  Needs no target: the
 * master's own waveform is read back on MISO through the 750R series resistor.
 * Returns 0 when the echoed frame header decodes correctly. */
int  sw_selftest(uint8_t *echo, uint32_t echo_len);

/* Drive PA7 as a plain GPIO and read PA6 back: proves the 750R link exists,
 * with no SPI or SWire timing involved.  out[] gets the PA6 level with PA7
 * low, high and released.  Returns 0 when PA6 followed PA7. */
int  sw_pintest(uint8_t *out);

/* Raw MISO samples of the most recent transfer (built-in logic analyser). */
const uint8_t *sw_last_raw(uint32_t *len);

#endif /* SWIRE_H */
